/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package trabprog;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;

/**
 *
 * @author Paula Costa
 */
public class NewJDialogListarJ extends javax.swing.JDialog {

    /**
     * Creates new form NewJDialogListarJ
     */
    public NewJDialogListarJ(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        carregarJogadores();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableJogadores = new javax.swing.JTable();
        jButtonFechar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Lista de todos os jogadores cadastrados");

        jTableJogadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableJogadores);

        jButtonFechar.setText("Fechar");
        jButtonFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trabprog/bola.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(374, 374, 374)
                        .addComponent(jButtonFechar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(179, 179, 179)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 678, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 66, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jButtonFechar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharActionPerformed
        // TODO add your handling code here:
         this.dispose();
    }//GEN-LAST:event_jButtonFecharActionPerformed
private void carregarJogadores() {
    try (Connection conn = ConexaoBD.getConnection()) {
        // Consulta SQL para buscar todos os jogadores com os dados relacionados
        String sql = """
            SELECT 
                Jogador.Cod_Jogador AS Código,
                Jogador.Nome_Jogador AS Nome,
                YEAR(CURDATE()) - YEAR(Jogador.DataNascimento) AS Idade,
                Jogador.Altura AS Altura,
                Pais.Nome_Pais AS País,
                Jogador.Sexo AS Sexo,
                Agente.Nome_Agente AS Agente,
                Posicao.Nome_Posicao AS Posição
            FROM 
                Jogador
            LEFT JOIN 
                Pais ON Jogador.Cod_Pais = Pais.Cod_Pais
            LEFT JOIN 
                Agente ON Jogador.Cod_Agente = Agente.Cod_Agente
            LEFT JOIN 
                Posicao ON Jogador.Cod_Posicao = Posicao.Cod_Posicao
            ORDER BY Nome
        """;

        try (PreparedStatement stmt = conn.prepareStatement(sql);
             ResultSet rs = stmt.executeQuery()) {

            // Modelo da tabela para exibir os jogadores
            DefaultTableModel model = new DefaultTableModel(
                new Object[]{"Código", "Nome", "Idade", "Altura", "País", "Sexo", "Agente", "Posição"}, 
                0
            );

            // Preenche a tabela com os resultados
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("Código"),
                    rs.getString("Nome"),
                    rs.getInt("Idade"),
                    rs.getDouble("Altura"),
                    rs.getString("País"),
                    rs.getString("Sexo"),
                    rs.getString("Agente"),
                    rs.getString("Posição")
                });
            }

            // Configura o modelo da tabela
            jTableJogadores.setModel(model);

            // Ajustando o tamanho das colunas
            jTableJogadores.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
            jTableJogadores.getColumnModel().getColumn(0).setPreferredWidth(50); // Código
            jTableJogadores.getColumnModel().getColumn(1).setPreferredWidth(170); // Nome
            jTableJogadores.getColumnModel().getColumn(2).setPreferredWidth(50);  // Idade
            jTableJogadores.getColumnModel().getColumn(3).setPreferredWidth(50);  // Altura
            jTableJogadores.getColumnModel().getColumn(4).setPreferredWidth(100); // País
            jTableJogadores.getColumnModel().getColumn(5).setPreferredWidth(40);  // Sexo
            jTableJogadores.getColumnModel().getColumn(6).setPreferredWidth(110); // Agente
            jTableJogadores.getColumnModel().getColumn(7).setPreferredWidth(110); // Posição
            jTableJogadores.setRowHeight(30);

        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Erro ao carregar jogadores: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }
}
public void setTabelaResultados(DefaultTableModel model) {
    // Define o modelo da tabela
    jTableJogadores.setModel(model);

    // Ajusta o modo de redimensionamento para evitar redimensionamento automático
    jTableJogadores.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);

    // Ajusta o tamanho das colunas dinamicamente
    for (int i = 0; i < jTableJogadores.getColumnCount(); i++) {
        switch (i) {
            case 0: // Código
                jTableJogadores.getColumnModel().getColumn(i).setPreferredWidth(100);
                break;
            case 1: // Nome
                jTableJogadores.getColumnModel().getColumn(i).setPreferredWidth(200);
                break;
            case 2: // Idade
                jTableJogadores.getColumnModel().getColumn(i).setPreferredWidth(80);
                break;
            case 3: // Altura
                jTableJogadores.getColumnModel().getColumn(i).setPreferredWidth(80);
                break;
            case 4: // País
                jTableJogadores.getColumnModel().getColumn(i).setPreferredWidth(150);
                break;
            case 5: // Sexo
                jTableJogadores.getColumnModel().getColumn(i).setPreferredWidth(50);
                break;
            case 6: // Agente
                jTableJogadores.getColumnModel().getColumn(i).setPreferredWidth(150);
                break;
            case 7: // Posição
                jTableJogadores.getColumnModel().getColumn(i).setPreferredWidth(150);
                break;
            default:
                jTableJogadores.getColumnModel().getColumn(i).setPreferredWidth(100);
        }
    }

    // Ajusta a altura das linhas
    jTableJogadores.setRowHeight(30);
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJDialogListarJ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJDialogListarJ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJDialogListarJ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJDialogListarJ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NewJDialogListarJ dialog = new NewJDialogListarJ(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFechar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableJogadores;
    // End of variables declaration//GEN-END:variables
}
