/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package trabprog;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
/**
 *
 * @author Paula Costa
 */
public class NewJDialogCarreira extends javax.swing.JDialog {

    /**
     * Creates new form NewJDialog3
     */
    public NewJDialogCarreira(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabelJogadorCarreira = new javax.swing.JLabel();
        jLabelTimeCarreira = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelGolsCarreira = new javax.swing.JLabel();
        jLabelAssistenciasCarreira = new javax.swing.JLabel();
        jLabelAmarelosCarreira = new javax.swing.JLabel();
        jLabelVermelhosCarreiras = new javax.swing.JLabel();
        jLabelMercadoCarreira = new javax.swing.JLabel();
        jTextFieldCodJogador = new javax.swing.JTextField();
        jTextFieldCodTime = new javax.swing.JTextField();
        jTextFieldTemporada = new javax.swing.JTextField();
        jTextFieldValorMercado = new javax.swing.JTextField();
        jTextFieldNumGols = new javax.swing.JTextField();
        jTextFieldNumAssist = new javax.swing.JTextField();
        jTextFieldNumCA = new javax.swing.JTextField();
        jTextFieldNumCV = new javax.swing.JTextField();
        jButtonCancelar = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Digite os dados para cadastrar uma nova carreira");

        jLabelJogadorCarreira.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelJogadorCarreira.setText("Código Jogador:");

        jLabelTimeCarreira.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelTimeCarreira.setText("Código Time:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Temporada:");

        jLabelGolsCarreira.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelGolsCarreira.setText("Número de Gols:");

        jLabelAssistenciasCarreira.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelAssistenciasCarreira.setText("Número de Assistências:");

        jLabelAmarelosCarreira.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelAmarelosCarreira.setText("Número de Cartões Amarelos:");

        jLabelVermelhosCarreiras.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelVermelhosCarreiras.setText("Número de Cartões Vermelhos:");

        jLabelMercadoCarreira.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelMercadoCarreira.setText("Valor de Mercado:");

        jTextFieldValorMercado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldValorMercadoActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trabprog/bola.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jButtonCancelar)
                        .addGap(80, 80, 80)
                        .addComponent(jButtonSalvar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelJogadorCarreira)
                                    .addComponent(jLabelAmarelosCarreira)
                                    .addComponent(jLabelVermelhosCarreiras)
                                    .addComponent(jLabelAssistenciasCarreira)
                                    .addComponent(jLabelGolsCarreira)
                                    .addComponent(jLabelMercadoCarreira)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabelTimeCarreira))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jTextFieldCodTime, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                        .addComponent(jTextFieldCodJogador, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jTextFieldValorMercado, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jTextFieldNumCV, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                        .addComponent(jTextFieldNumCA, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                        .addComponent(jTextFieldNumAssist, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                        .addComponent(jTextFieldNumGols, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jTextFieldTemporada, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(11, 11, 11)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelJogadorCarreira)
                    .addComponent(jTextFieldCodJogador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTimeCarreira)
                    .addComponent(jTextFieldCodTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldTemporada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMercadoCarreira)
                    .addComponent(jTextFieldValorMercado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelGolsCarreira)
                    .addComponent(jTextFieldNumGols, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAssistenciasCarreira)
                    .addComponent(jTextFieldNumAssist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAmarelosCarreira)
                    .addComponent(jTextFieldNumCA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelVermelhosCarreiras)
                    .addComponent(jTextFieldNumCV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancelar)
                    .addComponent(jButtonSalvar))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldValorMercadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldValorMercadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldValorMercadoActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        // TODO add your handling code here:
        String codJogador = jTextFieldCodJogador.getText().trim();
    String codTime = jTextFieldCodTime.getText().trim();
    String temporada = jTextFieldTemporada.getText().trim();
    String numGols = jTextFieldNumGols.getText().trim();
    String numAssist = jTextFieldNumAssist.getText().trim();
    String numCA = jTextFieldNumCA.getText().trim();
    String numCV = jTextFieldNumCV.getText().trim();
    String valorMercado = jTextFieldValorMercado.getText().trim();

    // Validação de entradas
    if (codJogador.isEmpty() || codTime.isEmpty() || temporada.isEmpty() || 
        numGols.isEmpty() || numAssist.isEmpty() || numCA.isEmpty() || 
        numCV.isEmpty() || valorMercado.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor, preencha todos os campos!", "Erro", JOptionPane.WARNING_MESSAGE);
        return;
    }

    try {
        int gols = Integer.parseInt(numGols);
        int assist = Integer.parseInt(numAssist);
        int ca = Integer.parseInt(numCA);
        int cv = Integer.parseInt(numCV);
        int valor = Integer.parseInt(valorMercado);

        // Insere no banco de dados
        try (Connection conn = ConexaoBD.getConnection()) {
            String sql = "INSERT INTO Carreira (Cod_Jogador, Cod_Time, Temporada, Num_Gols, Num_Assist, Num_CA, Num_CV, Valor_Mercado) VALUES (?, ?, ?, ?, ?, ?, ?, ?)";
            try (PreparedStatement stmt = conn.prepareStatement(sql)) {
                stmt.setString(1, codJogador);
                stmt.setString(2, codTime);
                stmt.setString(3, temporada);
                stmt.setInt(4, gols);
                stmt.setInt(5, assist);
                stmt.setInt(6, ca);
                stmt.setInt(7, cv);
                stmt.setInt(8, valor);

                stmt.executeUpdate();
                JOptionPane.showMessageDialog(this, "Carreira cadastrada com sucesso!");
                this.dispose(); // Fecha o diálogo após salvar
            }
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Verifique se todos os campos numéricos são válidos!", "Erro de Validação", JOptionPane.ERROR_MESSAGE);
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Erro ao cadastrar carreira: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
          int resposta = JOptionPane.showConfirmDialog(this, 
        "Tem certeza de que deseja cancelar o cadastro? Os dados preenchidos serão perdidos.",
        "Confirmação", 
        JOptionPane.YES_NO_OPTION, 
        JOptionPane.WARNING_MESSAGE);
    
    if (resposta == JOptionPane.YES_OPTION) {
        this.dispose(); // Fecha o JDialog
    }
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJDialogCarreira.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJDialogCarreira.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJDialogCarreira.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJDialogCarreira.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NewJDialogCarreira dialog = new NewJDialogCarreira(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelAmarelosCarreira;
    private javax.swing.JLabel jLabelAssistenciasCarreira;
    private javax.swing.JLabel jLabelGolsCarreira;
    private javax.swing.JLabel jLabelJogadorCarreira;
    private javax.swing.JLabel jLabelMercadoCarreira;
    private javax.swing.JLabel jLabelTimeCarreira;
    private javax.swing.JLabel jLabelVermelhosCarreiras;
    private javax.swing.JTextField jTextFieldCodJogador;
    private javax.swing.JTextField jTextFieldCodTime;
    private javax.swing.JTextField jTextFieldNumAssist;
    private javax.swing.JTextField jTextFieldNumCA;
    private javax.swing.JTextField jTextFieldNumCV;
    private javax.swing.JTextField jTextFieldNumGols;
    private javax.swing.JTextField jTextFieldTemporada;
    private javax.swing.JTextField jTextFieldValorMercado;
    // End of variables declaration//GEN-END:variables
}
