package trabprog;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Paula Costa
 */
public class NewJDialogJogador extends javax.swing.JDialog {

    public NewJDialogJogador(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1CodigoJogador = new javax.swing.JLabel();
        jLabelNomeJogador = new javax.swing.JLabel();
        jLabelNascimentoJogador = new javax.swing.JLabel();
        jLabelSexoJogador = new javax.swing.JLabel();
        jLabelAlturaJogador = new javax.swing.JLabel();
        jLabelPaisJogador = new javax.swing.JLabel();
        jLabelAgenteJogador = new javax.swing.JLabel();
        jLabelPosicaoJogador = new javax.swing.JLabel();
        jTextFieldCodigo = new javax.swing.JTextField();
        jTextFieldNome = new javax.swing.JTextField();
        jTextFieldDataNascimento = new javax.swing.JTextField();
        jTextFieldSexo = new javax.swing.JTextField();
        jTextFieldAltura = new javax.swing.JTextField();
        jTextFieldPais = new javax.swing.JTextField();
        jTextFieldAgente = new javax.swing.JTextField();
        jTextFieldPosicao = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButtonCancelarJogador = new javax.swing.JButton();
        jButtonSalvarJogador = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1CodigoJogador.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1CodigoJogador.setText("Código:");

        jLabelNomeJogador.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelNomeJogador.setText("Nome:");

        jLabelNascimentoJogador.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelNascimentoJogador.setText("Data de Nascimento:");

        jLabelSexoJogador.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelSexoJogador.setText("Sexo:");

        jLabelAlturaJogador.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelAlturaJogador.setText("Altura:");

        jLabelPaisJogador.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelPaisJogador.setText("País:");

        jLabelAgenteJogador.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelAgenteJogador.setText("Agente:");

        jLabelPosicaoJogador.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelPosicaoJogador.setText("Posição:");

        jTextFieldCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodigoActionPerformed(evt);
            }
        });

        jTextFieldPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPaisActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Digite os dados para cadastrar um novo jogador");

        jButtonCancelarJogador.setText("Cancelar");
        jButtonCancelarJogador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarJogadorActionPerformed(evt);
            }
        });

        jButtonSalvarJogador.setText("Salvar");
        jButtonSalvarJogador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarJogadorActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trabprog/bola.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelNascimentoJogador)
                            .addComponent(jLabelNomeJogador)
                            .addComponent(jLabel1CodigoJogador)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(110, 110, 110)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabelAlturaJogador)
                                            .addComponent(jLabelSexoJogador)
                                            .addComponent(jLabelPaisJogador))
                                        .addGap(31, 31, 31))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabelAgenteJogador)
                                        .addGap(28, 28, 28)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(102, 102, 102)
                                    .addComponent(jLabelPosicaoJogador)
                                    .addGap(28, 28, 28)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldPosicao, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldPais, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldAgente, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(178, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonCancelarJogador)
                        .addGap(78, 78, 78)
                        .addComponent(jButtonSalvarJogador)
                        .addGap(247, 247, 247))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1CodigoJogador))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNomeJogador))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNascimentoJogador)
                    .addComponent(jTextFieldDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSexoJogador))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAlturaJogador))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPaisJogador)
                    .addComponent(jTextFieldPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldAgente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAgenteJogador))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPosicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPosicaoJogador))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancelarJogador)
                    .addComponent(jButtonSalvarJogador))
                .addGap(53, 53, 53))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCodigoActionPerformed

    private void jButtonCancelarJogadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarJogadorActionPerformed
        // TODO add your handling code here:
        // Confirmação antes de fechar o diálogo
    int resposta = JOptionPane.showConfirmDialog(this, 
        "Tem certeza de que deseja cancelar o cadastro? Os dados preenchidos serão perdidos.",
        "Confirmação", 
        JOptionPane.YES_NO_OPTION, 
        JOptionPane.WARNING_MESSAGE);
    
    if (resposta == JOptionPane.YES_OPTION) {
        this.dispose(); // Fecha o JDialog
    }
    }//GEN-LAST:event_jButtonCancelarJogadorActionPerformed

    private void jButtonSalvarJogadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarJogadorActionPerformed
        // TODO add your handling code here:
      // Captura os valores dos campos
    String codJogador = jTextFieldCodigo.getText().trim();
    String nomeJogador = jTextFieldNome.getText().trim();
    String dataNascimento = jTextFieldDataNascimento.getText().trim();
    String sexo = jTextFieldSexo.getText().trim();
    String altura = jTextFieldAltura.getText().trim();
    String pais = jTextFieldPais.getText().trim();
    String agente = jTextFieldAgente.getText().trim();
    String posicao = jTextFieldPosicao.getText().trim();

    // Validação de entradas
    if (codJogador.isEmpty() || nomeJogador.isEmpty() || dataNascimento.isEmpty() || 
        sexo.isEmpty() || altura.isEmpty() || pais.isEmpty() || agente.isEmpty() || posicao.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor, preencha todos os campos!", "Campos obrigatórios", JOptionPane.WARNING_MESSAGE);
        return;
    }

    try {
        double alturaJogador = Double.parseDouble(altura); // Valida altura como número
        if (alturaJogador <= 0) {
            JOptionPane.showMessageDialog(this, "A altura deve ser maior que zero!", "Erro de Validação", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Insere no banco de dados
        try (Connection conn = ConexaoBD.getConnection()) {
            String sql = "INSERT INTO Jogador (Cod_Jogador, Nome_Jogador, DataNascimento, Sexo, Altura, Cod_Pais, Cod_Agente, Cod_Posicao) VALUES (?, ?, ?, ?, ?, ?, ?, ?)";
            try (PreparedStatement stmt = conn.prepareStatement(sql)) {
                stmt.setString(1, codJogador);
                stmt.setString(2, nomeJogador);
                stmt.setString(3, dataNascimento);
                stmt.setString(4, sexo);
                stmt.setDouble(5, alturaJogador);
                stmt.setString(6, pais);
                stmt.setString(7, agente);
                stmt.setString(8, posicao);

                stmt.executeUpdate();
                JOptionPane.showMessageDialog(this, "Jogador cadastrado com sucesso!");
                this.dispose(); // Fecha o diálogo após salvar
            }
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "A altura deve ser um número válido!", "Erro de Validação", JOptionPane.ERROR_MESSAGE);
    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Erro ao cadastrar jogador: " + e.getMessage(), "Erro no Banco de Dados", JOptionPane.ERROR_MESSAGE);
    }
        
    }//GEN-LAST:event_jButtonSalvarJogadorActionPerformed

    private void jTextFieldPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPaisActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJDialogJogador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJDialogJogador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJDialogJogador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJDialogJogador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NewJDialogJogador dialog = new NewJDialogJogador(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelarJogador;
    private javax.swing.JButton jButtonSalvarJogador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel1CodigoJogador;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelAgenteJogador;
    private javax.swing.JLabel jLabelAlturaJogador;
    private javax.swing.JLabel jLabelNascimentoJogador;
    private javax.swing.JLabel jLabelNomeJogador;
    private javax.swing.JLabel jLabelPaisJogador;
    private javax.swing.JLabel jLabelPosicaoJogador;
    private javax.swing.JLabel jLabelSexoJogador;
    private javax.swing.JTextField jTextFieldAgente;
    private javax.swing.JTextField jTextFieldAltura;
    private javax.swing.JTextField jTextFieldCodigo;
    private javax.swing.JTextField jTextFieldDataNascimento;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldPais;
    private javax.swing.JTextField jTextFieldPosicao;
    private javax.swing.JTextField jTextFieldSexo;
    // End of variables declaration//GEN-END:variables
}
