/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package trabprog;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
/**
 *
 * @author Paula Costa
 */
public class NewJDialogTime extends javax.swing.JDialog {

    /**
     * Creates new form NewJDialog1
     */
    public NewJDialogTime(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelCodigoTime = new javax.swing.JLabel();
        jLabelNomeTime = new javax.swing.JLabel();
        jLabelEstadioTime = new javax.swing.JLabel();
        jLabelCidadeTime = new javax.swing.JLabel();
        jLabelEstadoTime = new javax.swing.JLabel();
        jLabelPaisTime = new javax.swing.JLabel();
        jTextFieldCodTime = new javax.swing.JTextField();
        jTextFieldNomeTime = new javax.swing.JTextField();
        jTextFieldEstadioTime = new javax.swing.JTextField();
        jTextFieldCidadeTime = new javax.swing.JTextField();
        jTextFieldEstadoTime = new javax.swing.JTextField();
        jTextFieldPaisTime = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButtonCancelarTime = new javax.swing.JButton();
        jButtonSalvarTime = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelCodigoTime.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelCodigoTime.setText("Código:");

        jLabelNomeTime.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelNomeTime.setText("Nome:");

        jLabelEstadioTime.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelEstadioTime.setText("Estádio:");

        jLabelCidadeTime.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelCidadeTime.setText("Cidade:");

        jLabelEstadoTime.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelEstadoTime.setText("Estado:");

        jLabelPaisTime.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelPaisTime.setText("País:");

        jTextFieldEstadioTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEstadioTimeActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Digite os dados para cadastrar um novo time");

        jButtonCancelarTime.setText("Cancelar");
        jButtonCancelarTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarTimeActionPerformed(evt);
            }
        });

        jButtonSalvarTime.setText("Salvar");
        jButtonSalvarTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarTimeActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trabprog/bola.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonCancelarTime)
                .addGap(114, 114, 114)
                .addComponent(jButtonSalvarTime)
                .addGap(216, 216, 216))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelPaisTime)
                            .addComponent(jLabelEstadoTime))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldEstadoTime, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldPaisTime, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelEstadioTime)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldEstadioTime, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelCidadeTime)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldCidadeTime))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelCodigoTime)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldCodTime, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabelNomeTime)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldNomeTime, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCodigoTime)
                    .addComponent(jTextFieldCodTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldNomeTime, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNomeTime))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldEstadioTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEstadioTime))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCidadeTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCidadeTime))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldEstadoTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEstadoTime))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPaisTime)
                    .addComponent(jTextFieldPaisTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancelarTime)
                    .addComponent(jButtonSalvarTime))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldEstadioTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEstadioTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEstadioTimeActionPerformed

    private void jButtonSalvarTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarTimeActionPerformed
        // TODO add your handling code here:
        String codTime = jTextFieldCodTime.getText().trim();
    String nomeTime = jTextFieldNomeTime.getText().trim();
    String estadio = jTextFieldEstadioTime.getText().trim();
    String cidade = jTextFieldCidadeTime.getText().trim();
    String estado = jTextFieldEstadoTime.getText().trim();
    String codPais = jTextFieldPaisTime.getText().trim();

    // Validação de entradas
    if (codTime.isEmpty() || nomeTime.isEmpty() || estadio.isEmpty() || 
        cidade.isEmpty() || estado.isEmpty() || codPais.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Preencha todos os campos!", "Erro", JOptionPane.WARNING_MESSAGE);
        return;
    }

    try (Connection conn = ConexaoBD.getConnection()) {
        String sql = "INSERT INTO Time (Cod_Time, Nome_Time, Estadio_Jogo, Cidade, Estado, Cod_Pais) VALUES (?, ?, ?, ?, ?, ?)";
        try (PreparedStatement stmt = conn.prepareStatement(sql)) {
            stmt.setString(1, codTime);
            stmt.setString(2, nomeTime);
            stmt.setString(3, estadio);
            stmt.setString(4, cidade);
            stmt.setString(5, estado);
            stmt.setString(6, codPais);

            stmt.executeUpdate();
            JOptionPane.showMessageDialog(this, "Time cadastrado com sucesso!");
            this.dispose(); // Fecha o diálogo após salvar
        }
    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Erro ao cadastrar time: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_jButtonSalvarTimeActionPerformed

    private void jButtonCancelarTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarTimeActionPerformed
        // TODO add your handling code here:
        // Confirmação antes de fechar o diálogo
    int resposta = JOptionPane.showConfirmDialog(this, 
        "Tem certeza de que deseja cancelar o cadastro? Os dados preenchidos serão perdidos.",
        "Confirmação", 
        JOptionPane.YES_NO_OPTION, 
        JOptionPane.WARNING_MESSAGE);
    
    if (resposta == JOptionPane.YES_OPTION) {
        this.dispose(); // Fecha o JDialog
    }
    }//GEN-LAST:event_jButtonCancelarTimeActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJDialogTime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJDialogTime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJDialogTime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJDialogTime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NewJDialogTime dialog = new NewJDialogTime(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelarTime;
    private javax.swing.JButton jButtonSalvarTime;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelCidadeTime;
    private javax.swing.JLabel jLabelCodigoTime;
    private javax.swing.JLabel jLabelEstadioTime;
    private javax.swing.JLabel jLabelEstadoTime;
    private javax.swing.JLabel jLabelNomeTime;
    private javax.swing.JLabel jLabelPaisTime;
    private javax.swing.JTextField jTextFieldCidadeTime;
    private javax.swing.JTextField jTextFieldCodTime;
    private javax.swing.JTextField jTextFieldEstadioTime;
    private javax.swing.JTextField jTextFieldEstadoTime;
    private javax.swing.JTextField jTextFieldNomeTime;
    private javax.swing.JTextField jTextFieldPaisTime;
    // End of variables declaration//GEN-END:variables
}
