/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package trabprog;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;

/**
 *
 * @author Paula Costa
 */
public class NewJFrame extends javax.swing.JFrame {

    public class DatabaseConnection {

        private static final String URL = "jdbc:mysql://localhost:3306/TransferFUT";
        private static final String USER = "root"; // Substitua pelo seu usuário do MySQL
        private static final String PASSWORD = "root"; // Substitua pela sua senha do MySQL

        public static Connection getConnection() throws SQLException {
            return DriverManager.getConnection(URL, USER, PASSWORD);
        }
    }

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonSair = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCadastro = new javax.swing.JMenu();
        jMenuItemJogador = new javax.swing.JMenuItem();
        jMenuItemTime = new javax.swing.JMenuItem();
        jMenuInsercao = new javax.swing.JMenu();
        jMenuItemTransferencia = new javax.swing.JMenuItem();
        jMenuItemCarreira = new javax.swing.JMenuItem();
        jMenuAlterar = new javax.swing.JMenu();
        jMenuItemAlterarJogador = new javax.swing.JMenuItem();
        jMenuItemAlterarTransf = new javax.swing.JMenuItem();
        jMenuRelatorios = new javax.swing.JMenu();
        jMenuItemLJogador = new javax.swing.JMenuItem();
        jMenuItemLCarreira = new javax.swing.JMenuItem();
        jMenuItemLTransferencia = new javax.swing.JMenuItem();
        jMenuAjuda = new javax.swing.JMenu();
        jMenuItemAjuda = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TransferFUT");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trabprog/transferencias.png"))); // NOI18N

        jButtonSair.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        jMenuCadastro.setText("Cadastro");

        jMenuItemJogador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trabprog/jogador.png"))); // NOI18N
        jMenuItemJogador.setText("Jogador");
        jMenuItemJogador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemJogadorActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemJogador);

        jMenuItemTime.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trabprog/time oficial.png"))); // NOI18N
        jMenuItemTime.setText("Time");
        jMenuItemTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTimeActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemTime);

        jMenuBar1.add(jMenuCadastro);

        jMenuInsercao.setText("Inserção");

        jMenuItemTransferencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trabprog/icons8-transfer-20.png"))); // NOI18N
        jMenuItemTransferencia.setText("Transferência");
        jMenuItemTransferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTransferenciaActionPerformed(evt);
            }
        });
        jMenuInsercao.add(jMenuItemTransferencia);

        jMenuItemCarreira.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trabprog/carreira.png"))); // NOI18N
        jMenuItemCarreira.setText("Carreira");
        jMenuItemCarreira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCarreiraActionPerformed(evt);
            }
        });
        jMenuInsercao.add(jMenuItemCarreira);

        jMenuBar1.add(jMenuInsercao);

        jMenuAlterar.setText("Alterar");

        jMenuItemAlterarJogador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trabprog/time.png"))); // NOI18N
        jMenuItemAlterarJogador.setText("Jogador");
        jMenuItemAlterarJogador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAlterarJogadorActionPerformed(evt);
            }
        });
        jMenuAlterar.add(jMenuItemAlterarJogador);

        jMenuItemAlterarTransf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trabprog/transf.png"))); // NOI18N
        jMenuItemAlterarTransf.setText("Transferência");
        jMenuItemAlterarTransf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAlterarTransfActionPerformed(evt);
            }
        });
        jMenuAlterar.add(jMenuItemAlterarTransf);

        jMenuBar1.add(jMenuAlterar);

        jMenuRelatorios.setText("Relatórios");
        jMenuRelatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRelatoriosActionPerformed(evt);
            }
        });

        jMenuItemLJogador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trabprog/listar jog.png"))); // NOI18N
        jMenuItemLJogador.setText("Listar Jogadores");
        jMenuItemLJogador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLJogadorActionPerformed(evt);
            }
        });
        jMenuRelatorios.add(jMenuItemLJogador);

        jMenuItemLCarreira.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trabprog/listar carreira.png"))); // NOI18N
        jMenuItemLCarreira.setText("Listar Carreira");
        jMenuItemLCarreira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLCarreiraActionPerformed(evt);
            }
        });
        jMenuRelatorios.add(jMenuItemLCarreira);

        jMenuItemLTransferencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trabprog/listrar trasnf.png"))); // NOI18N
        jMenuItemLTransferencia.setText("Listar Transferências");
        jMenuItemLTransferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLTransferenciaActionPerformed(evt);
            }
        });
        jMenuRelatorios.add(jMenuItemLTransferencia);

        jMenuBar1.add(jMenuRelatorios);

        jMenuAjuda.setText("Ajuda");

        jMenuItemAjuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trabprog/ajuda.png"))); // NOI18N
        jMenuItemAjuda.setText("Pergunte Heveraldo");
        jMenuItemAjuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAjudaActionPerformed(evt);
            }
        });
        jMenuAjuda.add(jMenuItemAjuda);

        jMenuBar1.add(jMenuAjuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 952, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 952, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonSair)
                .addGap(420, 420, 420))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonSair)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemAjudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAjudaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemAjudaActionPerformed

    private void jMenuItemCarreiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCarreiraActionPerformed
        // TODO add your handling code here:
        NewJDialogCarreira dialog = new NewJDialogCarreira(this, true);
        dialog.setVisible(true);
    }//GEN-LAST:event_jMenuItemCarreiraActionPerformed

    private void jMenuItemLTransferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLTransferenciaActionPerformed
        // TODO add your handling code here:
        NewJDialogListarTrans listarTrans = new NewJDialogListarTrans(this, true);
        listarTrans.setVisible(true);
    }//GEN-LAST:event_jMenuItemLTransferenciaActionPerformed

    private void jMenuItemLCarreiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLCarreiraActionPerformed
        // TODO add your handling code here:

        NewJDialogLCarreira listarCarreiraDialog = new NewJDialogLCarreira(this, true);
        listarCarreiraDialog.setVisible(true); // 
    }//GEN-LAST:event_jMenuItemLCarreiraActionPerformed

    private void jMenuRelatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRelatoriosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuRelatoriosActionPerformed

    private void jMenuItemLJogadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLJogadorActionPerformed
        // TODO add your handling code here:
        NewJDialogListarJ dialog = new NewJDialogListarJ(this, true);
        dialog.setVisible(true);
    }//GEN-LAST:event_jMenuItemLJogadorActionPerformed

    private void jMenuItemAlterarJogadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAlterarJogadorActionPerformed
        // TODO add your handling code here:                                                   
        NewJDialogAlterarJog dialog = new NewJDialogAlterarJog(this, true);
        dialog.setVisible(true);

    }//GEN-LAST:event_jMenuItemAlterarJogadorActionPerformed

    private void jMenuItemTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTimeActionPerformed
        // TODO add your handling code here:
        NewJDialogTime cadastroTimeDialog = new NewJDialogTime(this, true);
        cadastroTimeDialog.setVisible(true);
    }//GEN-LAST:event_jMenuItemTimeActionPerformed

    private void jMenuItemJogadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemJogadorActionPerformed
        // TODO add your handling code here:
        NewJDialogJogador cadastroJogadorDialog = new NewJDialogJogador(this, true);
        cadastroJogadorDialog.setVisible(true);
    }//GEN-LAST:event_jMenuItemJogadorActionPerformed

    private void jMenuItemAlterarTransfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAlterarTransfActionPerformed
        // TODO add your handling code here:
         NewJDialogAlterarTransf dialog = new NewJDialogAlterarTransf(this, true);
        dialog.setVisible(true);
    }//GEN-LAST:event_jMenuItemAlterarTransfActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonSairActionPerformed

                                                 

    private void jMenuItemTransferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTransferenciaActionPerformed
        // TODO add your handling code here:
        NewJDialogTransferencia transferenciaDialog = new NewJDialogTransferencia(this, true);

        // Exibe o diálogo de forma modal
        transferenciaDialog.setVisible(true);
    }//GEN-LAST:event_jMenuItemTransferenciaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new NewJFrameIniciar().setVisible(true); // Inicia na tela do NewJFrameIniciar
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenuAjuda;
    private javax.swing.JMenu jMenuAlterar;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCadastro;
    private javax.swing.JMenu jMenuInsercao;
    private javax.swing.JMenuItem jMenuItemAjuda;
    private javax.swing.JMenuItem jMenuItemAlterarJogador;
    private javax.swing.JMenuItem jMenuItemAlterarTransf;
    private javax.swing.JMenuItem jMenuItemCarreira;
    private javax.swing.JMenuItem jMenuItemJogador;
    private javax.swing.JMenuItem jMenuItemLCarreira;
    private javax.swing.JMenuItem jMenuItemLJogador;
    private javax.swing.JMenuItem jMenuItemLTransferencia;
    private javax.swing.JMenuItem jMenuItemTime;
    private javax.swing.JMenuItem jMenuItemTransferencia;
    private javax.swing.JMenu jMenuRelatorios;
    // End of variables declaration//GEN-END:variables
}
