/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package trabprog;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;


/**
 *
 * @author Paula Costa
 */
public class NewJDialogLCarreira extends javax.swing.JDialog {

    /**
     * Creates new form NewJDialogLCarreira
     */
    public NewJDialogLCarreira(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldCodigo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButtonBuscar = new javax.swing.JButton();
        jButtonVoltar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Digite o código do jogador que deseja:");

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        jButtonVoltar.setText("Voltar");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trabprog/bola.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(69, 69, 69))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jButtonVoltar)
                            .addGap(95, 95, 95)
                            .addComponent(jButtonBuscar)
                            .addGap(112, 112, 112)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(199, 199, 199))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBuscar)
                    .addComponent(jButtonVoltar))
                .addGap(29, 29, 29)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        // TODO add your handling code here:
String codigoJogador = jTextFieldCodigo.getText().trim(); // Obtém o código do jogador digitado

if (codigoJogador.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Por favor, insira o código do jogador.", "Aviso", JOptionPane.WARNING_MESSAGE);
    return;
}

try (Connection conn = ConexaoBD.getConnection()) {
    // Consulta SQL ajustada para incluir nome do jogador, cartões, títulos e informações relacionadas
    String sql = """
        SELECT 
            Jogador.Nome_Jogador AS Nome_Jogador,
            Time.Nome_Time AS Nome_Time,
            Carreira.Temporada,
            Posicao.Nome_Posicao AS Posicao_Jogador,
            Carreira.Num_Gols,
            Carreira.Num_Assist,
            Carreira.Valor_Mercado,
            Carreira.Num_CA,
            Carreira.Num_CV,
            Titulos.Nome_Titulo AS Nome_Titulo
        FROM 
            Carreira
        INNER JOIN 
            Time ON Carreira.Cod_Time = Time.Cod_Time
        INNER JOIN 
            Jogador ON Carreira.Cod_Jogador = Jogador.Cod_Jogador
        INNER JOIN 
            Posicao ON Jogador.Cod_Posicao = Posicao.Cod_Posicao
        LEFT JOIN 
            Titulos ON Titulos.Cod_Jogador = Carreira.Cod_Jogador AND Titulos.Temporada = Carreira.Temporada
        WHERE 
            Carreira.Cod_Jogador = ?
    """;

    try (PreparedStatement stmt = conn.prepareStatement(sql)) {
        stmt.setString(1, codigoJogador);

        try (ResultSet rs = stmt.executeQuery()) {
            DefaultTableModel model = new DefaultTableModel(
                new Object[]{"Nome do Jogador", "Time", "Ano", "Posição", "Gols", "Assistências", "Valor de Mercado", "Amarelos", "Vermelhos", "Títulos"},
                0
            );

            boolean hasData = false;
            while (rs.next()) {
                hasData = true;
                model.addRow(new Object[]{
                    rs.getString("Nome_Jogador"),
                    rs.getString("Nome_Time"),
                    rs.getString("Temporada"),
                    rs.getString("Posicao_Jogador"),
                    rs.getInt("Num_Gols"),
                    rs.getInt("Num_Assist"),
                    rs.getDouble("Valor_Mercado"),
                    rs.getInt("Num_CA"),
                    rs.getInt("Num_CV"),
                    rs.getString("Nome_Titulo") != null ? rs.getString("Nome_Titulo") : "Nenhum"
                });
            }

            if (!hasData) {
                JOptionPane.showMessageDialog(this, "Nenhuma carreira encontrada para o jogador: " + codigoJogador, "Sem dados", JOptionPane.INFORMATION_MESSAGE);
                return;
            }

            // Exibe os resultados em um diálogo de listagem
            NewJDialogListagem dialog = new NewJDialogListagem(null, true);
            dialog.setTabelaResultados(model); // Configura o modelo da tabela
            dialog.setVisible(true); // Exibe o diálogo
        }
    }
} catch (SQLException e) {
    JOptionPane.showMessageDialog(this, "Erro ao buscar a carreira: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
    e.printStackTrace();
}


    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        // TODO add your handling code here:
         this.dispose();
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJDialogLCarreira.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJDialogLCarreira.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJDialogLCarreira.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJDialogLCarreira.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NewJDialogLCarreira dialog = new NewJDialogLCarreira(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextFieldCodigo;
    // End of variables declaration//GEN-END:variables
}
